services:
  user-service:
    build: ./user

  order-service:
    build: ./order
    depends_on:
      - user-service

  frontend:
    build: ./frontend
    ports:
      - "8080:5000"
    depends_on:
      - order-service
