services:
  user-service:
    build: .
    command: python user_app.py

  order-service:
    build: .
    command: python order_app.py
    depends_on:
      - user-service

  frontend:
    build: .
    command: python frontend_app.py
    ports:
      - "8080:5000"
    depends_on:
      - order-service
